#!/usr/bin/env bash
# Bash script that displays 'Best School' 10 times but for the 9th iteration, displays 'Best School' and then 'Hi' on a new line
# Use while loop and if statement only
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
