#!/usr/bin/env bash
# a Bash script that displays lines containing the 'bash' word
# Requirments
#	You cannot use pgrep
#	The third line of your script must be # shellcheck disable=SC2009
ps -faux | grep "bash"
