#!/usr/bin/env bash
# a Bash script that displays 'To infinity and beyond' indefinitely
# Requirements:
#	add a 'sleep 2' between each iteration of the loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
